### ISSUE TITLE
String literal property names cause errors during compilation

### ISSUE THREAD

**Issue by Aierie** [diez/diez#132]
Using Diez version 10.6.0

```
Error: Expected to find member with name: "contentBackground-1"
    at throwIfNullOrUndefined (/Users/michael/Documents/vase-design-tokens/design-language/node_modules/ts-morph/dist/ts-morph.js:127:15)
    at Symbol.getMemberOrThrow (/Users/michael/Documents/vase-design-tokens/design-language/node_modules/ts-morph/dist/ts-morph.js:17868:16)
    at exports.ProjectParser.processType (/Users/michael/Documents/vase-design-tokens/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:4608)
    at exports.ProjectParser.processType (/Users/michael/Documents/vase-design-tokens/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:5812)
    at exports.ProjectParser.run (/Users/michael/Documents/vase-design-tokens/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:7130)
```

The error above occurs whenever I have to use string literals for property names.

eg. 

```
const colors = {
  "15thItem": colors.red,
  "ui-1": colors.blue
}
```

It may be related to this issue on ts-morph:
https://github.com/dsherret/ts-morph/issues/820

**Comment by roperzh** [comment]
Hey @Aierie , thank you very much for the report and the help investigating the issue. I think this is worth fixing and publishing, I will ping you as soon as a new version is out.

**Comment by phil-lgr** [comment]
Same thing for enums:

```ts
const palette = {
  [ENUM.NAME1]: colors.red,
  "ui-1": colors.blue
}
```

Does not work either
