### ISSUE TITLE
Design Language Properties Not Compiling when Deeper Than First Level

### ISSUE THREAD

**Issue by phil-lgr** [diez/diez#139]
Steps to reproduce

```
git clone git@github.com:diez/diez.git
cd diez
yarn
cd examples/lorem-ipsum/design-language/
yarn
yarn demo
```

Then change lines 39-... to this:

```ts
const typography = {
   // put heading1 under a normal prop
    nested: {
        heading1: new Typograph({
            font: Fonts.SourceSansPro.Regular,
            fontSize: 24,
            color: palette.text,
        }),
    },

  body: new Typograph({
    font: Fonts.SourceSansPro.Regular,
    fontSize: 18,
    color: palette.text,
    alignment: TextAlignment.Center,
  }),

  caption: new Typograph({
    font: Fonts.SourceSansPro.Regular,
    fontSize: 14,
    color: palette.caption,
  }),
}
```

Expected behavior:

`heading1` typograph outputs under `nested`

Actual behavior: heading1 is not outputted

```ts
class Typography {
  constructor({
    body = {font: {file: {src: "assets/SourceSansPro-Regular.ttf", type: "font"}, name: "SourceSansPro-Regular", fallbacks: ["sans-serif"], weight: 400, style: "normal"}, fontSize: 18, color: {h: 0.6666666666666666, s: 1, l: 0.03137254901960784, a: 1}, lineHeight: -1, letterSpacing: 0, alignment: "center", decoration: []},
    caption = {font: {file: {src: "assets/SourceSansPro-Regular.ttf", type: "font"}, name: "SourceSansPro-Regular", fallbacks: ["sans-serif"], weight: 400, style: "normal"}, fontSize: 14, color: {h: 0.7085385878489326, s: 0.8565400843881857, l: 0.5352941176470588, a: 1}, lineHeight: -1, letterSpacing: 0, alignment: "natural", decoration: []}
  } = {}) {
```

**Comment by phil-lgr** [comment]
If one of you @roperzh @zackbrown can point me out where to start looking, I’d be happy to try and add a test case

Also I’d want to know why enums don’t work with the current prefab implementation

**Comment by phil-lgr** [comment]
In https://github.com/diez/diez/blob/master/src/framework/engine/test/prefab.test.ts#L22

I extended the test to include a nested prop:

```ts
class FooPrefab extends prefab<FooData>() {
  defaults = {
    justbar: ['bar'],
    foobar: new FooString(),
    nested: {
      foobar: new FooString({
        value: 'nestedBar',
      }),
    },
  };
}
```

And it's getting caugh in an infinite loop:

```bash
Philippes-iMac:diez phil$ yarn test --scope @diez/engine
yarn run v1.22.4
$ lerna run test --scope @diez/engine
lerna notice cli v3.13.1
lerna info filter [ '@diez/engine' ]
lerna info Executing command in 1 package: "yarn run test"
lerna ERR! yarn run test exited 1 in '@diez/engine'
lerna ERR! yarn run test stdout:
$ jest
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
warning package.json: License should be a valid SPDX license expression
PASS test/serialization.test.ts
FAIL test/prefab.test.ts
  ● prefab › serializes through sanitized inputs and nested subcomponents

    RangeError: Maximum call stack size exceeded

      81 |    * Generic serialization instructions. These can be overridden as needed.
      82 |    */
    > 83 |   serialize () {
         |            ^
      84 |     return serialize(this.sanitize(Object.assign(this.defaults, this.overrides)));
      85 |   }
      86 | 

      at Proxy.serialize (src/prefab.ts:83:12)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:13:28)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:26:23)
      at Proxy.serialize (src/prefab.ts:84:12)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:13:28)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:26:23)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:26:23)
      at Proxy.serialize (src/prefab.ts:84:12)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:13:28)
      at Object.<anonymous>.exports.serialize (src/serialization.ts:26:23)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        3.34s, estimated 6677s
Ran all test suites.
```

Here is the debug config:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Jest debug current file",
      "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
      "cwd": "${workspaceFolder}/src/framework/engine/",
      "args": ["${relativeFile}", "--no-cache", "--config=${workspaceFolder}/src/framework/engine/jest.config.js"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
```

**Comment by roperzh** [comment]
Thanks for the report! I will paste here some of the bits we discussed in Slack for the sake of overcommunication.

if you are in a hurry or don't want to spend time debugging, this:

```ts
const nested = {
  heading1: new Typograph({
      font: Font.fromFile('assets/SourceSansPro-Regular.ttf'),
      fontSize: 24,
      color: Color.hex('#FFFFFF'),
  }),
}
const typography = {
  nested,
}
```
outputs:

```js
class Nested {
  constructor({
    heading1 = {font: {file: {src: "assets/SourceSansPro-Regular.ttf", type: "font"}, name: "SourceSansPro-Regular", fallbacks: ["sans-serif"], weight: 400, style: "normal"}, fontSize: 24, color: {h: 0, s: 0, l: 1, a: 1}, lineHeight: -1, letterSpacing: 0, alignment: "natural", decoration: []}
  } = {}) {
    this.heading1 = new Typograph(heading1);
  }
}
module.exports.Nested = Nested;
class Typography {
  constructor({
    nested = {},
  } = {}) {
    this.nested = new Nested(nested);
}
```

and this should work:

```js
ds.typography.nested.heading1
```

having said that, support to nest objects directly would be great, the problem seems to be in the parser, [over here](https://github.com/diez/diez/blob/master/src/compiler/compiler-core/src/parser.ts#L280-L284) to be precise.

**Comment by phil-lgr** [comment]
Just pasting this for documentation purposes

Rob's overview of what diez does

- It compiles the source TypeScript code to JavaScript:  https://github.com/diez/diez/blob/220f76cd06c265e82e6da3adfe04bd744923e9b3/src/compiler/compiler-core/src/parser.ts#L545
- Requires the compiled design system: https://github.com/diez/diez/blob/220f76cd06c265e82e6da3adfe04bd744923e9b3/src/compiler/compiler-core/src/compiler.ts#L295-L300
- Using the TypeScript API and the runtime values from the compiled code it builds a tree of components: https://github.com/diez/diez/blob/220f76cd06c265e82e6da3adfe04bd744923e9b3/src/compiler/compiler-core/src/compiler.ts#L302-L313
- Using the tree of components, each target compiler can build source code for the target platform (for example the web compiler): 
https://github.com/diez/diez/blob/220f76cd06c265e82e6da3adfe04bd744923e9b3/src/compiler/targets/src/targets/web.compiler.ts

Do we have a write up of this somewhere in the docs? That would be very useful for new contributor like me

**Comment by phil-lgr** [comment]
So I've added:

![image](https://user-images.githubusercontent.com/9644867/88562905-4a658a00-cfff-11ea-99c1-dbcf4937efeb.png)

In the Primitives.ts

When when I debug in the parser, I think we have a problem in this area:

![image](https://user-images.githubusercontent.com/9644867/88562971-610be100-cfff-11ea-81d9-c8550d602dd6.png)

Looks like we don't get the correct type for a nested object

**Comment by phil-lgr** [comment]
so at this point:

![image](https://user-images.githubusercontent.com/9644867/88563701-471ece00-d000-11ea-95fc-fb41addb1a4e.png)

it looks like the parser supports class declaration or variable declaration but not object litteral?

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/88565258-51da6280-d002-11ea-85a3-addf282fc4c0.png)

In this case, `nested` is a PropertyAssignment:

![image](https://user-images.githubusercontent.com/9644867/88565374-80583d80-d002-11ea-8c50-5c8865522f71.png)

Ok, and it looks like we don't handle Properties assignment here as well:

![image](https://user-images.githubusercontent.com/9644867/88565626-dfb64d80-d002-11ea-843a-46135bbc46a5.png)

I think I understand what's is going on, but, I have no clue on how to add handling of PropertyAssignment

**Comment by phil-lgr** [comment]
Added other tests cases which outlines other bugs:

```ts
const colorBlack = Color.hex('#000');
const colorRed = Color.hex('#CE0000');

const nestedPrefabComponent = new NestedPrefabComponent({
  child,
  diez: 1,
  color: colorBlack,
});

const nestedPrefabComponentWithRedColor = new NestedPrefabComponent({
  child,
  diez: 1,
  color: colorRed,
});

export const primitives = {
    ... // other props
    nestedPrefabs: nestedPrefabComponent,
    nestedPrefabsWithOverride: nestedPrefabComponentWithRedColor,
};
```


when nesting prefab in a prefab, there is no CSS / SCSS output:

![image](https://user-images.githubusercontent.com/9644867/89082472-1e7a3980-d35c-11ea-81c7-14c7cd3aaea2.png)
