### ISSUE TITLE
Sanitize property names before generating SDK

### ISSUE THREAD

**Issue by roperzh** [diez/diez#41]
Prevent property names with reserved/invalid words in target lang, for example it is possible to define:

```ts
class CornerRadii {
  default = 4;
}
```

which compiles to the following in the JS SDK:

```ts
class CornerRadii {
  constructor({
    default = 4
  } = {}) {
    this.default = default;
  }
}
```

and it's invalid ES6 because `default` is a keyword.

**Comment by alo9507** [comment]
I may pick this up for Swift transpilation. What's the desired behavior if a reserved word is used in the design language? Throw a compile-time exception along the lines of:

`Cannot use property name 'self' for target 'swift' because 'self' is a reserved token in Swift`

Thanks.

**Comment by zackbrown** [comment]
Hey @alo9507 your contribution would be very welcome, and yes that sounds like a perfectly fine approach + error message. 

It sounds like you've dug in a bit already and may already have your bearings, but if helpful we recommend starting by reading [CONTRIBUTING.md](https://github.com/diez/diez/blob/master/CONTRIBUTING.md) to set up your dev-env, then to start exploring from [the entry-point for the iOS compiler target](https://github.com/diez/diez/blob/master/src/compiler/targets/src/targets/ios.ts) 

If you'd like to chat about anything more in-depth, you can expand the conversation here or feel free to join our [Community Slack](https://join.slack.com/t/dieznative/shared_invite/enQtNzEzNzM2OTg4NDA1LTA4NWZiMTNlZTgzNTY3Yzg2ODdjY2Y1MzBjMjdlY2FlNjljMmI3ZTgzMmQ4ODk1MDdlMTcyMTUzMjNmZWI4YjU) where we have a #contributions channel for this purpose.

**Comment by alo9507** [comment]
Thanks @zackbrown. I'll see what I can do this weekend. I'll comment here by end of day Sunday (Feb 2) to lyk whether or not I've completed it, will complete it, or if I've abandoned it and someone else should pick it up.

**Comment by alo9507** [comment]
Failed to complete it this weekend. will keep working at it throughout the week however.

**Comment by zackbrown** [comment]
Thanks for the excellent communication — looking forward to seeing what you come up with.

**Comment by amadeu01** [comment]
@roperzh I don't know whether this is related or not.
But I got `Expected to find member with name:` when the name of the asset starts with number. 
Like, `16Something`, then I got:
```
yarn run v1.21.1
$ diez compile -t ios --carthage
Validating project structure at /Users/amadeu.filho/Developer/design-system/design-language...
Compiling project...
Error: Expected to find member with name: '16Something'
    at throwIfNullOrUndefined (/Users/Developer/design-system/design-language/node_modules/ts-morph/dist/ts-morph.js:127:15)
    at Symbol.getMemberOrThrow (/Users/Developer/-design-system/design-language/node_modules/ts-morph/dist/ts-morph.js:17868:16)
    at exports.ProjectParser.processType (/Users/Developer/-design-system/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:4608)
    at exports.ProjectParser.processType (/Users/Developer/-design-system/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:5812)
    at exports.ProjectParser.run (/Users/Developer/-design-system/design-language/node_modules/@diez/compiler-core/lib/parser.js:1:7130)
    at async module.exports (/Users/Developer/-design-system/design-language/node_modules/@diez/compiler-core/lib/commands/compile.action.js:1:522)
    at async Command.<anonymous> (/Users/Developer/-design-system/design-language/node_modules/@diez/cli-core/lib/cli.js:1:712)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
